=== cazadoxs/UnityGames/Docs/Modding/schemas/doctrine.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "doctrine",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "weights": {
      "type": "object",
      "additionalProperties": {
        "type": "number",
        "format": "float"
      }
    },
    "preferredPlans": {
      "type": "object",
      "additionalProperties": {
        "type": "number",
        "format": "float"
      }
    },
    "deployment": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/inglesa_1415.json
{
  "id": "estandartes:doctrine/inglesa_1415",
  "name": "Doctrina inglesa (s. XV)",
  "weights": {
    "estandartes:unit/arqueros_arco_largo": 0.7,
    "estandartes:unit/hombres_de_armas": 0.25,
    "estandartes:unit/caballeria_pesada": 0.05
  },
  "preferredPlans": {
    "provoke_defend": 0.5
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/angevina.json
{
  "id": "estandartes:doctrine/angevina",
  "name": "Doctrina angevina",
  "weights": {
    "estandartes:unit/hombres_de_armas": 0.4,
    "estandartes:unit/ballesteros": 0.4,
    "estandartes:unit/lanceros": 0.2
  },
  "preferredPlans": {
    "defense_in_depth": 0.4
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/castellana.json
{
  "id": "estandartes:doctrine/castellana",
  "name": "Doctrina castellana",
  "weights": {
    "estandartes:unit/caballeria_pesada": 0.25,
    "estandartes:unit/jinetes": 0.15,
    "estandartes:unit/lanceros": 0.2,
    "estandartes:unit/ballesteros": 0.15,
    "estandartes:unit/levas": 0.25
  },
  "preferredPlans": {
    "anvil_hammer": 0.2,
    "frontal": 0.1
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/escocesa.json
{
  "id": "estandartes:doctrine/escocesa",
  "name": "Doctrina escocesa",
  "weights": {
    "estandartes:unit/lanceros_escoceses": 0.75,
    "estandartes:unit/arqueros": 0.05,
    "estandartes:unit/caballeria_ligera": 0.05,
    "estandartes:unit/hostigadores": 0.15
  },
  "preferredPlans": {
    "wait_and_strike": 0.5,
    "defend_high_ground": 0.2
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/inglesa_1297.json
{
  "id": "estandartes:doctrine/inglesa_1297",
  "name": "Doctrina inglesa (finales del s. XIII)",
  "weights": {
    "estandartes:unit/caballeria_pesada": 0.2,
    "estandartes:unit/hombres_de_armas": 0.25,
    "estandartes:unit/arqueros": 0.2,
    "estandartes:unit/lanceros": 0.2,
    "estandartes:unit/levas": 0.15
  },
  "preferredPlans": {
    "frontal": 0.3
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/navarra.json
{
  "id": "estandartes:doctrine/navarra",
  "name": "Doctrina navarra",
  "weights": {
    "estandartes:unit/caballeria_pesada": 0.3,
    "estandartes:unit/lanceros": 0.25,
    "estandartes:unit/hostigadores": 0.15,
    "estandartes:unit/levas": 0.3
  },
  "preferredPlans": {
    "frontal": 0.3
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/almohade.json
{
  "id": "estandartes:doctrine/almohade",
  "name": "Doctrina almohade",
  "weights": {
    "estandartes:unit/voluntarios": 0.25,
    "estandartes:unit/caballeria_ligera": 0.25,
    "estandartes:unit/arqueros_a_caballo": 0.1,
    "estandartes:unit/arqueros": 0.15,
    "estandartes:unit/guardia_del_califa": 0.1,
    "estandartes:unit/lanceros": 0.15
  },
  "preferredPlans": {
    "attrition_envelop": 0.5
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/doctrines/francesa_1415.json
{
  "id": "estandartes:doctrine/francesa_1415",
  "name": "Doctrina francesa (s. XV)",
  "weights": {
    "estandartes:unit/hombres_de_armas": 0.45,
    "estandartes:unit/caballeria_pesada": 0.2,
    "estandartes:unit/ballesteros": 0.15,
    "estandartes:unit/arqueros": 0.1,
    "estandartes:unit/levas": 0.1
  },
  "preferredPlans": {
    "frontal": 0.4
  },
  "deployment": {
    "ShockInfantry": "Center",
    "PolearmInfantry": "Center",
    "Ranged": "Front",
    "Skirmisher": "Front",
    "ShockCavalry": "Wings",
    "LightCavalry": "Wings",
    "Engineer": "Reserve",
    "Command": "Escort"
  }
}
