=== cazadoxs/UnityGames/Docs/Modding/schemas/unit.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "unit",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "archetype": {
      "$ref": "#/definitions/Archetype"
    },
    "capabilities": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "weapons": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "armor": {
      "$ref": "#/definitions/ArmorValues"
    },
    "stats": {
      "$ref": "#/definitions/UnitStats"
    },
    "personality": {
      "$ref": "#/definitions/PersonalityRanges"
    },
    "squadSize": {
      "type": "integer",
      "format": "int32"
    },
    "cost": {
      "type": "integer",
      "format": "int32"
    },
    "era": {
      "type": "string"
    },
    "culture": {
      "type": "string"
    },
    "voices": {
      "type": "string"
    }
  },
  "definitions": {
    "Archetype": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "ShockInfantry",
        "PolearmInfantry",
        "LineInfantry",
        "Ranged",
        "Skirmisher",
        "ShockCavalry",
        "LightCavalry",
        "Artillery",
        "Engineer",
        "Command"
      ],
      "enum": [
        "ShockInfantry",
        "PolearmInfantry",
        "LineInfantry",
        "Ranged",
        "Skirmisher",
        "ShockCavalry",
        "LightCavalry",
        "Artillery",
        "Engineer",
        "Command"
      ]
    },
    "ArmorValues": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "cut": {
          "type": "number",
          "format": "float"
        },
        "pierce": {
          "type": "number",
          "format": "float"
        },
        "blunt": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "UnitStats": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "health": {
          "type": "number",
          "format": "float"
        },
        "mountHealth": {
          "type": "number",
          "format": "float"
        },
        "morale": {
          "type": "number",
          "format": "float"
        },
        "discipline": {
          "type": "number",
          "format": "float"
        },
        "walk": {
          "type": "number",
          "format": "float"
        },
        "run": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "PersonalityRanges": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "courage": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "aggression": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "skill": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "discipline": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        },
        "experience": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          }
        }
      }
    }
  }
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/lanceros_escoceses.json
{
  "id": "estandartes:unit/lanceros_escoceses",
  "name": "Lanceros escoceses",
  "archetype": "PolearmInfantry",
  "capabilities": [
    "AntiCavalryFormation",
    "Shield"
  ],
  "weapons": [
    "estandartes:weapon/lanza_larga",
    "estandartes:weapon/espada_corta"
  ],
  "armor": {
    "cut": 0.2,
    "pierce": 0.15,
    "blunt": 0.1
  },
  "stats": {
    "health": 100,
    "mountHealth": 0,
    "morale": 70,
    "discipline": 70,
    "walk": 1.4,
    "run": 5.2
  },
  "personality": {
    "courage": [
      0.6,
      0.9
    ],
    "aggression": [
      0.5,
      0.85
    ],
    "skill": [
      0.3,
      0.7
    ],
    "discipline": [
      0.5,
      0.85
    ],
    "experience": [
      0.3,
      0.7
    ]
  },
  "squadSize": 100,
  "cost": 8,
  "era": "medieval",
  "culture": "escocesa"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/paveseros.json
{
  "id": "estandartes:unit/paveseros",
  "name": "Paveseros",
  "archetype": "PolearmInfantry",
  "capabilities": [
    "Pavise",
    "Shield"
  ],
  "weapons": [
    "estandartes:weapon/lanza",
    "estandartes:weapon/espada_corta"
  ],
  "armor": {
    "cut": 0.35,
    "pierce": 0.25,
    "blunt": 0.2
  },
  "stats": {
    "health": 100,
    "mountHealth": 0,
    "morale": 55,
    "discipline": 60,
    "walk": 1.2,
    "run": 4.5
  },
  "personality": {
    "courage": [
      0.4,
      0.7
    ],
    "aggression": [
      0.2,
      0.5
    ],
    "skill": [
      0.3,
      0.6
    ],
    "discipline": [
      0.4,
      0.8
    ],
    "experience": [
      0.2,
      0.6
    ]
  },
  "squadSize": 40,
  "cost": 7,
  "era": "medieval"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/fyrd.json
{
  "id": "estandartes:unit/fyrd",
  "name": "Fyrd (milicia)",
  "archetype": "PolearmInfantry",
  "capabilities": [
    "Shield",
    "ShieldWall"
  ],
  "weapons": [
    "estandartes:weapon/lanza",
    "estandartes:weapon/daga"
  ],
  "armor": {
    "cut": 0.15,
    "pierce": 0.1,
    "blunt": 0.1
  },
  "stats": {
    "health": 100,
    "mountHealth": 0,
    "morale": 45,
    "discipline": 30,
    "walk": 1.4,
    "run": 5.5
  },
  "personality": {
    "courage": [
      0.3,
      0.7
    ],
    "aggression": [
      0.3,
      0.7
    ],
    "skill": [
      0.1,
      0.4
    ],
    "discipline": [
      0.1,
      0.4
    ],
    "experience": [
      0.0,
      0.3
    ]
  },
  "squadSize": 80,
  "cost": 4,
  "era": "medieval",
  "culture": "noroccidental_temprana"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/hombres_de_armas.json
{
  "id": "estandartes:unit/hombres_de_armas",
  "name": "Hombres de armas",
  "archetype": "ShockInfantry",
  "capabilities": [
    "Shield",
    "ShieldWall"
  ],
  "weapons": [
    "estandartes:weapon/espada",
    "estandartes:weapon/maza"
  ],
  "armor": {
    "cut": 0.6,
    "pierce": 0.45,
    "blunt": 0.3
  },
  "stats": {
    "health": 100,
    "mountHealth": 0,
    "morale": 70,
    "discipline": 70,
    "walk": 1.3,
    "run": 5.0
  },
  "personality": {
    "courage": [
      0.5,
      0.9
    ],
    "aggression": [
      0.4,
      0.8
    ],
    "skill": [
      0.5,
      0.9
    ],
    "discipline": [
      0.5,
      0.9
    ],
    "experience": [
      0.4,
      0.9
    ]
  },
  "squadSize": 60,
  "cost": 12,
  "era": "medieval"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/ballesteros.json
{
  "id": "estandartes:unit/ballesteros",
  "name": "Ballesteros",
  "archetype": "Ranged",
  "capabilities": [
    "Reload",
    "Pavise"
  ],
  "weapons": [
    "estandartes:weapon/ballesta",
    "estandartes:weapon/espada_corta"
  ],
  "armor": {
    "cut": 0.35,
    "pierce": 0.25,
    "blunt": 0.2
  },
  "stats": {
    "health": 100,
    "mountHealth": 0,
    "morale": 50,
    "discipline": 60,
    "walk": 1.3,
    "run": 5.2
  },
  "personality": {
    "courage": [
      0.3,
      0.7
    ],
    "aggression": [
      0.2,
      0.5
    ],
    "skill": [
      0.4,
      0.8
    ],
    "discipline": [
      0.4,
      0.8
    ],
    "experience": [
      0.3,
      0.7
    ]
  },
  "squadSize": 60,
  "cost": 10,
  "era": "medieval"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/arqueros_a_caballo.json
{
  "id": "estandartes:unit/arqueros_a_caballo",
  "name": "Arqueros a caballo",
  "archetype": "LightCavalry",
  "capabilities": [
    "Mounted",
    "HorseArcher"
  ],
  "weapons": [
    "estandartes:weapon/arco_compuesto",
    "estandartes:weapon/espada"
  ],
  "armor": {
    "cut": 0.25,
    "pierce": 0.15,
    "blunt": 0.15
  },
  "stats": {
    "health": 100,
    "mountHealth": 200,
    "morale": 55,
    "discipline": 55,
    "walk": 4.0,
    "run": 13
  },
  "personality": {
    "courage": [
      0.4,
      0.8
    ],
    "aggression": [
      0.4,
      0.8
    ],
    "skill": [
      0.5,
      0.9
    ],
    "discipline": [
      0.4,
      0.7
    ],
    "experience": [
      0.4,
      0.8
    ]
  },
  "squadSize": 30,
  "cost": 18,
  "era": "medieval"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/guardia_del_califa.json
{
  "id": "estandartes:unit/guardia_del_califa",
  "name": "Guardia del califa",
  "archetype": "ShockInfantry",
  "capabilities": [
    "Shield",
    "AntiCavalryFormation"
  ],
  "weapons": [
    "estandartes:weapon/lanza_larga",
    "estandartes:weapon/espada"
  ],
  "armor": {
    "cut": 0.45,
    "pierce": 0.35,
    "blunt": 0.25
  },
  "stats": {
    "health": 100,
    "mountHealth": 0,
    "morale": 90,
    "discipline": 90,
    "walk": 1.3,
    "run": 5.0
  },
  "personality": {
    "courage": [
      0.8,
      1.0
    ],
    "aggression": [
      0.4,
      0.8
    ],
    "skill": [
      0.6,
      0.9
    ],
    "discipline": [
      0.8,
      1.0
    ],
    "experience": [
      0.6,
      0.9
    ]
  },
  "squadSize": 60,
  "cost": 16,
  "era": "medieval",
  "culture": "andalusi_magrebi"
}

=== cazadoxs/UnityGames/Estandartes/Assets/StreamingAssets/Mods/estandartes/data/units/caballeros_normandos.json
{
  "id": "estandartes:unit/caballeros_normandos",
  "name": "Caballeros normandos",
  "archetype": "ShockCavalry",
  "capabilities": [
    "Mounted",
    "Shield"
  ],
  "weapons": [
    "estandartes:weapon/lanza_caballeria",
    "estandartes:weapon/espada"
  ],
  "armor": {
    "cut": 0.55,
    "pierce": 0.45,
    "blunt": 0.3
  },
  "stats": {
    "health": 100,
    "mountHealth": 250,
    "morale": 75,
    "discipline": 60,
    "walk": 3.0,
    "run": 11
  },
  "personality": {
    "courage": [
      0.6,
      0.9
    ],
    "aggression": [
      0.6,
      0.9
    ],
    "skill": [
      0.5,
      0.9
    ],
    "discipline": [
      0.5,
      0.8
    ],
    "experience": [
      0.5,
      0.9
    ]
  },
  "squadSize": 25,
  "cost": 25,
  "era": "medieval",
  "culture": "noroccidental_temprana"
}
